-- Tabla ESTUDIANTES
CREATE TABLE "PROYECTOQR"."ESTUDIANTES" (
  "ESTUDIANTEID" NUMBER DEFAULT "PROYECTOQR",
  "NOMBRE" VARCHAR2(100 BYTE),
  "APELLIDO" VARCHAR2(100 BYTE),
  "CODIGOQR" VARCHAR2(255 BYTE),
  "NUMEROCARNET" VARCHAR2(100 BYTE),
  "TELEFONO" VARCHAR2(100 BYTE),
  "DIRECCION" VARCHAR2(100 BYTE),
  "ANIO" VARCHAR2(4 BYTE),
  "SEDE" VARCHAR2(100 BYTE),
  "USUARIO" VARCHAR2(50 BYTE),
  "CONTRASENA" VARCHAR2(200 BYTE)
)
TABLESPACE "TBS_PROYECTOQR";

-- Tabla AUDITORIA
CREATE TABLE "PROYECTOQR"."AUDITORIA" (
  "ID_AUDITORIA" NUMBER NOT NULL,
  "ESTUDIANTEID" NUMBER,
  "FECHA" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  "TIPOACCION" VARCHAR2(20 BYTE),
  "DESCRIPCION" VARCHAR2(200 BYTE)
)
TABLESPACE "TBS_PROYECTOQR";

-- Tabla HISTORIALESTUDIANTES
CREATE TABLE "PROYECTOQR"."HISTORIALESTUDIANTES" (
  "ID_HISTORIAL" NUMBER NOT NULL,
  "ACCION" VARCHAR2(20 BYTE),
  "DESCRIPCION" VARCHAR2(500 BYTE),
  "FECHA" TIMESTAMP(6) DEFAULT SYSTIMESTAMP
)
TABLESPACE "TBS_PROYECTOQR";

-- Tabla MARCAJES
CREATE TABLE "PROYECTOQR"."MARCAJES" (
  "MARCAJEID" NUMBER DEFAULT "PROYECTOQR",
  "ESTUDIANTEID" NUMBER,
  "FECHAHORA" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
  "TIPO" VARCHAR2(10 BYTE)
)
TABLESPACE "TBS_PROYECTOQR";