-- Restricciones para MARCAJES
ALTER TABLE "PROYECTOQR"."MARCAJES" MODIFY ("MARCAJEID" NOT NULL ENABLE);
ALTER TABLE "PROYECTOQR"."MARCAJES" ADD PRIMARY KEY ("MARCAJEID")
TABLESPACE "TBS_PROYECTOQR" ENABLE;

-- Restricciones para ESTUDIANTES
ALTER TABLE "PROYECTOQR"."ESTUDIANTES" MODIFY ("ESTUDIANTEID" NOT NULL ENABLE);
ALTER TABLE "PROYECTOQR"."ESTUDIANTES" ADD PRIMARY KEY ("ESTUDIANTEID")
TABLESPACE "TBS_PROYECTOQR" ENABLE;

ALTER TABLE "PROYECTOQR"."ESTUDIANTES" ADD UNIQUE ("CODIGOQR")
TABLESPACE "TBS_PROYECTOQR" ENABLE;

-- Restricciones para HISTORIALESTUDIANTES
ALTER TABLE "PROYECTOQR"."HISTORIALESTUDIANTES" ADD PRIMARY KEY ("ID_HISTORIAL")
TABLESPACE "TBS_PROYECTOQR" ENABLE;

-- Clave foránea en MARCAJES
ALTER TABLE "PROYECTOQR"."MARCAJES" ADD FOREIGN KEY ("ESTUDIANTEID")
  REFERENCES "PROYECTOQR"."ESTUDIANTES" ("ESTUDIANTEID") ENABLE;