-- 1) Asegurar que CONTRASENA soporte hash (mismo nombre, nuevo uso)
ALTER TABLE PROYECTOQR.ESTUDIANTES
  MODIFY (CONTRASENA VARCHAR2(255 CHAR));

-- 2) Agregar ROL (simple) y ESTADO (A/I)
ALTER TABLE PROYECTOQR.ESTUDIANTES
  ADD (
    ROL    VARCHAR2(30 CHAR) DEFAULT 'ESTUDIANTE' NOT NULL,
    ESTADO CHAR(1 CHAR)      DEFAULT 'A'          NOT NULL
  );

-- 3) Restringir ESTADO a valores válidos
ALTER TABLE PROYECTOQR.ESTUDIANTES
  ADD CONSTRAINT CK_ESTUDIANTES_ESTADO_AI
  CHECK (ESTADO IN ('A','I'));

-- (OPCIONAL, si quieres evitar duplicados de usuario por mayúsc/minúsculas)
-- CREATE UNIQUE INDEX UX_ESTUDIANTES_USUARIO_LC
--   ON PROYECTOQR.ESTUDIANTES (LOWER(USUARIO));

-- (Opcional) Documentación rápida
COMMENT ON COLUMN PROYECTOQR.ESTUDIANTES.CONTRASENA IS 'Almacena HASH de contraseña (no texto plano), generado en backend';
COMMENT ON COLUMN PROYECTOQR.ESTUDIANTES.ROL        IS 'Rol básico: p.ej. ESTUDIANTE, DOCENTE, ADMIN';
COMMENT ON COLUMN PROYECTOQR.ESTUDIANTES.ESTADO     IS 'A=Activo, I=Inactivo';
